# Generated by Django 4.1 on 2022-09-29 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('sku', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('about', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Not Available', 'Not Available')], max_length=100)),
                ('img', models.ImageField(upload_to='images/product-pics/')),
                ('is_featured', models.BooleanField(default=False)),
                ('stock_count', models.IntegerField(default=1)),
                ('rating_count', models.IntegerField(default=0)),
                ('review_count', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
                ('category', models.ManyToManyField(to='vendor.category')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='products.tag')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
